### ISSUE TITLE
联网导入功能的一些建议

### ISSUE THREAD

**Issue by keleus** [tinymins/JX3_MY_DATA#1]
## 个人想法
github对于大部分数据作者来说可能操作难度较大，经过尝试发现只需要有`meta.json`、`data.jx3dat`、`README.md`三个文件，并在json里定义相对链接即可导入数据。所以计划在自己服务器上搭建一个数据分享网站。
## 一个建议
能否由第三方网站提供一个feeds.json文件用于提供订阅该网站收录的全部数据？（不过没有也问题不大）

**Comment by tinymins** [comment]
完全可以的，你只要提供meta.json文件地址就可以

**Comment by tinymins** [comment]
前排提示：你要有足够预算抵御数据下载的流量，这得考虑好就行，玩家下载起数据来带宽消耗还是很凶的

**Comment by keleus** [comment]
团队同步的时候是否会通过数据所在网站（如github）获取呢，还是直接玩家之间同步？
插件获取数据更新是只有在打开从互联网导入的界面时请求吗？

如果是玩家之间同步的话，可能服务器需要的带宽成本会低一些，就可以只当做是个下载网站。（CDN什么的不存在的，1Mbps慢慢来）

另外，json里的`data.jx3dat`文件是不是可以使用绝对路径（完整的网址），这样能让他们自己存在别的云盘之类的地方。

**Comment by tinymins** [comment]
1. 无法通过玩家同步，因为数据量过大，聊天频道一次只能发400个字符左右，这数据上来就几百K，只能通过分享下载地址实现。
2. 可以使用绝对路径，但是云盘一般直接访问会因为cookie等问题拒绝请求的，欢迎试试哪个云盘提供永久下载链接。

**Comment by tinymins** [comment]
> 团队同步的时候是否会通过数据所在网站（如github）获取呢，还是直接玩家之间同步？
> 插件获取数据更新是只有在打开从互联网导入的界面时请求吗？
> 
> 如果是玩家之间同步的话，可能服务器需要的带宽成本会低一些，就可以只当做是个下载网站。（CDN什么的不存在的，1Mbps慢慢来）
> 
> 另外，json里的`data.jx3dat`文件是不是可以使用绝对路径（完整的网址），这样能让他们自己存在别的云盘之类的地方。

这里给个数据吧，菊花之前和我说他服务器晚上高峰期下载速度在 40M/s 的样子（注意是大M），现在端游PVE没有当年那么盛世，他当年的流量也仅供参考

**Comment by codexss** [comment]
@tinymins 

jsdelivr有提供github的镜像，可以考虑把链接换成他们的cdn链接，他们的cdn在国内也有服务器  

https://www.jsdelivr.com  

https://cdn.jsdelivr.net/gh/tinymins/JX3_MY_DATA/MY_TeamMon/README.md

**Comment by tinymins** [comment]
> @tinymins
> 
> jsdelivr有提供github的镜像，可以考虑把链接换成他们的cdn链接，他们的cdn在国内也有服务器
> 
> https://www.jsdelivr.com
> 
> https://cdn.jsdelivr.net/gh/tinymins/JX3_MY_DATA/MY_TeamMon/README.md

可，感谢！
